### ISSUE TITLE
The example no longer works after the last Arduino IDE update

### ISSUE THREAD

**Issue by emanuelelaface** [esp32beans/ESP32_USB_Host_HID#1]
I had the working HID HOST Example, then Arduino IDE updated to the latest Arduino-esp32 (the 3.0.0) and now nothing compiles anymore.
The first error is `Compilation error: 'gpio_config_t' does not name a type; did you mean 'uart_config_t'?` that is fixed adding the include for gpio, but then it rises another one that is `Compilation error: invalid conversion from 'void*' to 'TaskHandle_t' {aka 'tskTaskControlBlock*'} [-fpermissive]` and is where I am stuck now.

I also saw that on ESP32 forum they are talking about implementing the USB HUB on the ESP32 IDF, so I was wondering if this project will follow and add it also for the Arduino-Ide.
Thanks a lot for this project.

**Comment by esp32beans** [comment]
The following fixes the compile errors but I can't find my esp32 box so I have not test the change yet.

```diff
@@ -2,10 +2,11 @@
  * SPDX-FileCopyrightText: 2022-2023 Espressif Systems (Shanghai) CO LTD
  *
  * SPDX-License-Identifier: Unlicense OR CC0-1.0
  */
 
+#include "driver/gpio.h"
 #include "usb/usb_host.h"
 
 #include "hid_host.h"
 #include "hid_usage_keyboard.h"
 #include "hid_usage_mouse.h"
@@ -506,11 +507,11 @@ static void usb_lib_task(void *arg) {
       .skip_phy_setup = false,
       .intr_flags = ESP_INTR_FLAG_LEVEL1,
   };
 
   ESP_ERROR_CHECK(usb_host_install(&host_config));
-  xTaskNotifyGive(arg);
+  xTaskNotifyGive((TaskHandle_t)arg);
 
   while (gpio_get_level(APP_QUIT_PIN) != 0) {
     uint32_t event_flags;
     usb_host_lib_handle_events(portMAX_DELAY, &event_flags);

```

**Comment by emanuelelaface** [comment]
Thanks, this fix works perfectly.
